### ISSUE TITLE
Dependencies not showing up in game mod list

### ISSUE THREAD

**Issue by KrazyWolf1991** [herotc/hero-dbc#2]
Im trying to use hero rotation in world of warcraft. I've downloaded both dependencies but, hero-dbc isn't showing up in the mod list in game.

**Comment by Cilraaz** [comment]
If it doesn't show up in your addon list, then you've installed it incorrectly.

**Comment by KrazyWolf1991** [comment]
then how am i supposed to properly install it?

**Comment by Cilraaz** [comment]
Download the zip from [here](https://github.com/herotc/hero-dbc/releases/download/9.0.5.02/HeroDBC-9.0.5.02.zip) and unzip it in your Interface\Addons folder, or you can install it from [CurseForge](https://www.curseforge.com/wow/addons/herodbc).

**Comment by KrazyWolf1991** [comment]
i installed if from curseforge. i've never had to unzip a file before so how do i do that??

**Comment by KrazyWolf1991** [comment]
nevermind, it's working lol. sorry for the bother. thank you for the help
