### ISSUE TITLE
[Bug]: Hero DBC. SpellGCD quite a few duplicate keys in the table

### ISSUE THREAD

**Issue by OverHealz** [herotc/hero-dbc#4]
### What version of HeroDBC are you using?

10.1.7.51536 

### What is the issue?

-- Generated using WoW 10.1.7.51536 client data on 2023-10-12T00:04:15.900409.

**Comment by mhunk** [comment]
`Generated using WoW 9.2.7.45114 client data on 2022-08-21T22:49:27.486125.`

Data is generated from blizz
