### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Silvenium** [herotc/hero-dbc#5]
### What version of HeroDBC are you using?

10.2.7.03

### What is the issue?

I was having trouble getting the files to be created after using the symlink.bat file...  I ended up having to change some of the writing, and I'm not sure if that was intentional or not? 

I'm not sure; I barely touch any computer writing type stuff. ^_^; I only changed the third line:
### |
 **v**
 
> REM Modify the WoWRep var so it match you own setup. Make sure you have it surrounded by double quotes
>REM WoWRep  : World of warcraft main directory
>set WoWRep="C:\Program Files (x86)\World of Warcraft"
>set CWD="%cd%"

**Comment by Cilraaz** [comment]
1. ~~This doesn't relate to HeroDBC in any way.~~ Forgot HeroDBC does actually have a symlink file... it's just not in the root of the github. Sorry. Long day.
2. Yes, you need to update the paths for the script to work, as the note says.
